frequency: 30

sensor_timeout: 10

two_d_mode: true

odom_frame: odom
base_link_frame: base_link

odom0: /odom
odom0_config: [true, true, false,  # Use pose (x, y, z)
              false, false, true,   # Use twist (roll, pitch, z)
              false, false, false,
              false, false, false,
              true, true, false]  # Ignore acceleration (x, y, z)


imu0: /rugbot2/imu
imu0_config: [false, false, false,  # Ignore orientation (x, y, z)
              false, false, false,
              false, false, false,
              false, false, true,   # Use angular velocity (roll, pitch, z)
              false, false, false]
